---
title: "Workflow PeptideSC: Normalization"
abstract: >
  The page describe the Normalization step of the Single-Cell Peptide Worflow.

output:
    BiocStyle::html_document:
        highlight: tango
        toc: false
        number_sections: FALSE
date: 11 February 2026
link-citations: true
---
# Normalization

The `Normalization` step reduces biases introduced at any preliminary stage, as to make samples more comparable. Though not a full batch effect correction method (which can be required depending on the experimental design), it can limit some simple batch effects. During this step, peptide abundances are essentially rescaled between samples of the same conditions or of all conditions.

This step allows the selection of a normalization method from several available options, which are described below. If the chosen normalization method is not satisfactory, it is always possible to reset the step and start again. 

***

### Normalization

The `Normalization` step offers a number of different normalization method, that are described below. The parameters to be defined vary depending on the selected method.

The left side of the interface is used to select the normalization method and configure the settings associated with the chosen method. Once pleased with the selected options, click on `Run` at the top to apply the normalization to the data.
The central area of the interface displays multiple graphs. The graphs on the left shows the intensity distributions for each sample. For the top one, it is possible to hide a specified sample from the graph by clicking on its name in the legend. The bottom one can be switched from violin plot to a boxplot by clicking on the button above the graph.
The graph on the right provides a way to visually compare the quantitative data before and after normalization. This plot shows the influence of the normalization method. 

If the normalization outcome is unsatisfactory, click “Reset” to return to the initial state and adjust the normalization method or its parameters.

##### Description of parameters and options :
###### **`Normalization method`**
Select for the drop-down menu the normalization method to be used. It is worth noting that each method has its own set of parameters, which are described further below.

The possible options are as follows:

- `None` : No normalization method is applied, the quantitative data is left unchanged. No need to validate, directly go to next step.
- `GlobalQuantileAlignment` : Aligns the quantiles of intensity distributions across all samples. (This method should be used cautiously, as it imposes a high-impact normalization. Broadly speaking, the abundances are replaced by their order statistics). As no other parameters are needed for this option, no additional settings are displayed upon selection.
- `SumByColumns` : Normalizes each abundance value by the total abundance of its corresponding sample. Un-logged intensities are used for processing. This method assumes the total amount of biological material is equal in all the samples.
- `QuantileCentering` : Aligns the intensity distributions to a specific quantile, e.g., the median or a lower quantile, either across all samples or within each condition.
- `MeanCentering` : Aligns the intensity distributions to their means, either across all samples or within each condition. Optionally, unit variance can be enforced.
- `LOESS` : Applies a cyclic LOESS normalization, either across all samples or within each condition. The intensity values are normalized by means of a local regression model of the difference of intensities as function of the median intensity value (Cleveland, 1979) (see Smyth (2005) for implementation details).
- `vsn` : Applies the Variance Stabilization Normalization method, either across all samples or within each condition (Huber et al., 2002).

###### **`Normalization type`**
*Available for every method except `GlobalQuantileAlignment`.*

This parameter allows to indicate whether the method is applied to the entire dataset at once (`overall`) or whether each condition is normalized independently (`within conditions`).

###### **`Span`**
*Available only for the `LOESS` method.*

This corresponds to the proportion of the other analytes that are considered to perform the regression. The value must be a float between 0 and 1. 

###### **`Include variance reduction`**
*Available only for the `MeanCentering` method.*

This specifies whether variance reduction is performed during normalization, meaning the distribution variances are scaled to 1.

###### **`Normalization quantile`**
*Available only for the `QuantileCentering` method.*

This indicate the quantile of the intensity distribution that is used as reference. The value must be a float between 0 and 1. The most classically used is the median (quantile 0.5), but other quantiles can aslo be useful, depending on the dataset. Notably, as the lower limit of quantitation is roughly constant over the samples, relying on a lower quantile such as 0.15 can be efficient to align the signal/noise ratios.

###### **`Type of selection`**
*Available only for the `SumByColumns`, `QuantileCentering` and `MeanCentering` method.*

This setting applies normalization only to the selected peptides, leaving the others unchanged. Several selection methods are available.

The possible options are as follows:

- `None` : No selection. All peptides are normalized. 
- `List` : Use the `Select peptide` selector to choose peptides. The selected peptides are displayed in the violin and box plots and are the only ones shown in the right-hand graph. Only the selected peptides will be normalized.
- `Random` : Enter an integer n in `Random` to select n peptides at random from the dataset. Only the n randomly selected peptides will be normalized.
- `Column` : Select a column with boolean values using `Column of rowData` to indicate which peptides to retain. This option is available only if such column exists in rowData. Only the selected peptides will be normalized.


###### **`Synchronise with selection above`**
*Available only for the `SumByColumns`, `QuantileCentering` and `MeanCentering` method.*

This option synchronizes the graphs with the peptides selected above.

***

### Save

Click on `Run` on the left side to validate the step. 
The normalized dataset can be downloaded through the `xlsx` or `qf` button, depending on the desired file type.
It is possible to visualize the normalized data, as well as viewing all informations related to the normalization applied, by clicking the `EDA` button on the right side of the timeline.
