---
title: "Workflow PeptideSC: Description"
abstract: >
  The page describe the different steps of the Single-Cell Peptide Worflow.

output:
    BiocStyle::html_document:
        highlight: tango
        toc: false
        number_sections: FALSE
date: 30 mai 2024
link-citations: true
---
# Peptide Workflow
This workflow is a precursor- or peptide-level workflow. It allows to make a complete statistical analysis up to the selection of differentially expressed proteins in the contrasted conditions. 
At any point during the workflow, you can access the dataset information and various graphs by clicking on EDA at the top right of the screen.

The workflow is comprised of 5 steps : `Filtering`, `Normalization`, `Imputation`, `Aggregation` and `DifferentialAnalysis`. Details for each steps are provided below. 

Additional details on the steps and sub-steps are available in the `Description` tab for each step.

***

### Filtering
The `Filtering` step aims to remove peptides irrelevant to the analysis. Some peptides may correspond to contaminants or decoy sequences, while others may contain too many missing values to be reliably quantified. Filtering is performed using the quantitative data tags or the metadata, which include all non-quantitative variables from the original dataset. 

This step is based on defining queries based on user-selected parameters, such as the number of missing values within or across biological conditions, contaminant annotations, or decoy flags, to either retain or discard selected peptides. Multiple filtering steps can be applied sequentially, with each filter operating on the dataset produced by the previous one.

It contains 2 sub-steps : `Cell metadata filtering` and `Variable filtering`.

***

### Normalization
The `Normalization` step reduces biases introduced at any preliminary stage, as to make samples more comparable. Though not a full batch effect correction method (which can be required depending on the experimental design), it can limit some simple batch effects. During this step, peptide abundances are essentially rescaled between samples of the same conditions or of all conditions.

This step allows the selection of a normalization method from several available options. If the chosen normalization method is not satisfactory, it is always possible to reset the step and start again. 

It contains 1 sub-step : `Normalization`.

***

### Imputation
The `Imputation` step imputes missing values to produce a complete dataset. Theorically, imputation effectively creates estimated measurements rather than true experimental observations and should therefore be avoided whenever possible. In practice, most algorithms required subsequently cannot handle missing values, and even methods that claim robustness to missing data typically rely on implicit or explicit imputation, offering no real alternative. Therefore, this is a step that should not be overlooked and requires caution.
Imputed values use a different color code and tags than observed values, making it possible to track which proteins have been imputed.

This step allows the selection of a imputation method from several available options.

It contains 1 sub-step : `Imputation`.

***

### Aggregation
...

It contains 1 sub-step : `Aggregation`.

***

### DifferentialAnalysis
...

It contains 5 sub-steps : `Scenario`, `Fold-Change`, `Fine tuning`, `P-value calibration` and `FDR control`.
