---
title: "Workflow Protein: Imputation"
abstract: >
  The page describe the Imputation step of the Protein Worflow.

output:
    BiocStyle::html_document:
        highlight: tango
        toc: false
        number_sections: FALSE
date: 12 February 2026
link-citations: true
---
# Imputation

The `Imputation` step imputes missing values to produce a complete dataset. Theorically, imputation effectively creates estimated measurements rather than true experimental observations and should therefore be avoided whenever possible. In practice, most algorithms required subsequently cannot handle missing values, and even methods that claim robustness to missing data typically rely on implicit or explicit imputation, offering no real alternative. Therefore, this is a step that should not be overlooked and requires caution.
Imputed values use a different color code and tags than observed values, making it possible to track which proteins have been imputed.

This step allows the selection of a imputation method from several available options, which are described below. The imputation process is divided into two parts to account for the nature of the missing values (POV or MEC).

***

### POV Imputation

The `POV Imputation` step offers a number of different imputation method, that are described below. The parameters to be defined vary depending on the selected method. Only missing values identified as “POV” (Partially Observed Values) are imputed at this stage. A value is classified as a POV if at least one observation exists for that protein within the same condition.

The left side of the interface is used to select the imputation method and configure the settings associated with the chosen method. Once pleased with the selected options, click on `Run` at the top to apply the imputation to the data.
The table in the middle summarizes the number of missing values. After the imputation is applied, a second line summarizing the number of values imputed. If the `Det quantile` is selected, a second table will show under the first one indicating the values that will be used for the imputation.
The first graph under below the tables displays density plots showing the distribution of partially observed values for each condition. The x-axis corresponds to the mean intensity of a protein in a condition, while the y-axis indicates the number of observed values for that protein under the same condition. In general, it can be observed that the distribution tends to shift towards higher values when fewer missing values are present. This is a sign that at least some of the missing values originate from proteins that are below the lower limit of the mass spectrometer. 
The second graph is a heatmap of the proteins mean value according to their distribution of missing values across the conditions. Each line corresponds a protein, that have been reordered so as to cluster the proteins that have a similar amount of missing values distributed in the same way over the conditions. Likewise, the columns do not depicts a specific sample but rather any sample belonging to the given condition, as the samples have been reordered to focus on patterns of missing values. Each line is colored to represent the mean abundance value within each condition : red indicates high intensities and yellow low intensities. 

##### Description of parameters and options :
###### **`Algorithm for POV`**
Select for the drop-down menu the imputation method to be used. It is worth noting that each method has its own set of parameters, which are described further below.

The possible options are as follows:

- `None` : No imputation method is applied, the quantitative data is left unchanged. No need to validate, directly go to next step.
- `slsa` : Standing for Structured Least Square Adaptative. This is a regression based imputation method which account for a possible hierachical design. As no other parameters are needed for this option, no additional settings are displayed upon selection.
- `Det quantile` : This method imputes each missing value within a sample using a fixed deterministic value, typically chosen as a low quantile of that sample’s intensity distribution. When selected, a table will appear in the central part indicating the values that will be used for the imputation.
- `KNN` : Standing for K-nearest neighbors. It proposes to estimate each missing value by the mean of the observed values of other proteins with a similar intensity pattern, called neighbors.

###### **`Quantile`**
*Available only for the `Det quantile` method.*

This parameter indicate the quantile used as the reference value. The value must be a float between 0 and 100.

###### **`Factor`**
*Available only for the `Det quantile` method.*

This corresponds to the multiplying factor to apply to the chosen quantile value. The value must be a float.

###### **`Neighbors`**
*Available only for the `KNN` method.*

This corresponds to the number of neighbors to account for when using the KNN imputation method.


***

### MEC Imputation
The `MEC Imputation` step offers a number of different imputation method, that are described below. The parameters to be defined vary depending on the selected method. Only missing values identified as “MEC” (Missing in the Entire Condition) are imputed at this stage. A value is classified as a MEC if all the intensity values are missing for this protein in the condition considered. Imputing these values is inherently risky, as the absence of observed data makes any imputation arbitrary and may introduce poorly adjusted values into the dataset. Alternatively, MEC can be left unchanged, although this may hinder subsequent processing, or they can be removed during the filtering step and handled separately. However, excluding them in this way prevents their inclusion in downstream statistical analyses.

The left side of the interface is used to select the imputation method and configure the settings associated with the chosen method. Once pleased with the selected options, click on `Run` at the top to apply the imputation to the data.
The table in the middle summarizes the number of missing values. After the imputation is applied, a second line summarizing the number of values imputed. If the `Det quantile` is selected, a second table will show under the first one indicating the values that will be used for the imputation.
The first graph under below the tables displays density plots showing the distribution of partially observed values for each condition. The x-axis corresponds to the mean intensity of a protein in a condition, while the y-axis indicates the number of observed values for that protein under the same condition. In general, it can be observed that the distribution tends to shift towards higher values when fewer missing values are present. This is a sign that at least some of the missing values originate from proteins that are below the lower limit of the mass spectrometer. 
The second graph is a heatmap of the proteins mean value according to their distribution of missing values across the conditions. Each line corresponds a protein, that have been reordered so as to cluster the proteins that have a similar amount of missing values distributed in the same way over the conditions. Likewise, the columns do not depicts a specific sample but rather any sample belonging to the given condition, as the samples have been reordered to focus on patterns of missing values. Each line is colored to represent the mean abundance value within each condition : red indicates high intensities and yellow low intensities. 

###### **`Algorithm for MEC`**
Select for the drop-down menu the imputation method to be used. It is worth noting that each method has its own set of parameters, which are described further below.

The possible options are as follows:

- `None` : No imputation method is applied, the quantitative data is left unchanged. No need to validate, directly go to next step.
- `Det quantile` : This method imputes each missing value within a sample using a fixed deterministic value, typically chosen as a low quantile of that sample’s intensity distribution. When selected, a table will appear in the central part indicating the values that will be used for the imputation.
- `Fixed value` : Impute all MEC with a specific value. While simple, this method should be used carefully as it may lead to important data distortion.

###### **`Quantile`**
*Available only for the `Det quantile` method.*

This parameter indicate the quantile used as the reference value. The value must be a float between 0 and 100.

###### **`Factor`**
*Available only for the `Det quantile` method.*

This corresponds to the multiplying factor to apply to the chosen quantile value. The value must be a float.

###### **`Fixed value`**
*Available only for the `Fixed value` method.*

This specifies the fixed value used to impute all MEC.

***

### Save

Click on `Run` on the left side to validate the step. 
The imputed dataset can be downloaded through the `xlsx` or `qf` button, depending on the desired file type.
It is possible to visualize the imputed data, as well as viewing all informations related to the imputation applied, by clicking the `EDA` button on the right side of the timeline.
